# Fetching the latest node image on alpine linux
FROM node:18-alpine

# Setting up the work directory
WORKDIR /react-app

# Installing dependencies
COPY ./package*.json /react-app

RUN npm install

RUN npm i -g serve

# Copying all the files in our project
COPY . .

RUN npm run build

EXPOSE 3000

CMD [ "serve", "-s", "dist" ]